### ISSUE TITLE
How to show it in the browser tab and how to tell the site ID?

### ISSUE THREAD

**Issue by beceha** [tsteur/piwik-livetab-plugin#1]
Hi, I use the newest Piwik version and installed your plugin today, so far so good.

a)
But I cannot find any help file or advice on how to show it "in a browser tab" as seen in the screenshot.

b)
In the plugin's settings I cannot find where and how to "tell" the plugin to show me the values of which site ID. I have 8 sites form 8 domains in my Piwik installation.

Thanks.

**Comment by kbotnen** [comment]
Hi,
- It shows in the piwik browser tab.
- It shows the site you have selected (i.e in the piwik overview).

The documentation is lacking on this one, It took me a few minutes before I noticed.
- k -

**Comment by tsteur** [comment]
Exactly, it always shows the value of the current selected site in the same browser tab. I will have a look re docs.
